name: Build Schema

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jieba pypinyin opencc requests
    - name: Run git commands
      run: |
        git clone https://github.com/ha-pin/rime-cloverpinyin.git
        cd rime-cloverpinyin
        git submodule update --init
        git -C chinese-dictionary-3.6million lfs install
        git -C chinese-dictionary-3.6million lfs pull
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Build schema
      run: |
        ./rime-cloverpinyin/build.sh
    - name: Pack schema
      run: |
        ./rime-cloverpinyin/pack.sh ver.${{ steps.date.outputs.date }}
    - name: Upload to github pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./rime-cloverpinyin/data
